### ISSUE TITLE
simplescoring crashes on setup

### ISSUE THREAD

**Issue by outsideoiler** [tkallsen/simplescoring-ipsc-support#2]
Have iPhone 12 Pro, iOS 16.5. Can setup a name or two and a stage but whatever more I try to do simple scoring crashes and I need to restart. On restart all names or stages are gone, blanc again.
Would be nice to solve this since the software looks really easy, straight forward. Would like to use it.
Thank you
Wolfgang

**Comment by tkallsen** [comment]
Unfortunately I'm missing instrumentation on the iOS side, so I don't have any insights. On the todo list for the next version.

For now, I can only give you generic advice like uninstalling and then reinstalling, and see if it resolves the issue. If the app data is removed you should get the introduction screens, otherwise you need to find some way to clear it.

**Comment by tkallsen** [comment]
New version out now (1.5.4), with updated dependencies and improved logging. Please give it another try.

**Comment by tkallsen** [comment]
Stale.
